spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/kids-db}
    username: ${JDBC_DATABASE_USERNAME:unicorn_user}
    password: ${JDBC_DATABASE_PASSWORD:magical_password}
    driver-class-name: org.postgresql.Driver
server:
  port: ${PORT:8080}